### ISSUE TITLE
VideoCall not working 

### ISSUE THREAD

**Issue by Nirmal-ICPL** [QuickBlox/quickblox-react-native-samples#26]
Hello,

I 'm using webrtc-sample project and done all the required setup. I'm able to run the application.
After login, i'm able to select user and then nothing happens.

How can i verify video call feature? pls check below snap

![IMG_DAD47E9F2D1B-1](https://user-images.githubusercontent.com/39950692/148387670-fadf4f5e-9775-405b-bac3-7db8ae61a2ab.jpeg)

**Comment by Nirmal-ICPL** [comment]
Hello,

Can anybody help me here? Am i doing something wrong or miss something?

**Comment by oleksandr-shvetsov-qb** [comment]
Hello @Nirmal-ICPL ,
From the screenshot you've provided it seems that not all images were loaded (or not displayed for some reason). Could you please confirm that this screenshot was taken on a physical device? Have you tried to reload application? Have you made any changes to sample application code?

**Comment by Nirmal-ICPL** [comment]
Hello @oleksandr-shvetsov-qb 

Thanks for the update !!

Yes, I'm running app on iPhone-6S with iOS-14.6

I try to reload the app and re-run the app after cleaning project but getting the same issue.

I have made one change in PodFile due to i was facing issue 
`
  post_install do |installer|
    ## Fix for XCode 12.5
    find_and_replace("../node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm",
    "_initializeModules:(NSArray<id<RCTBridgeModule>> *)modules", "_initializeModules:(NSArray<Class> *)modules")
    find_and_replace("../node_modules/react-native/ReactCommon/turbomodule/core/platform/ios/RCTTurboModuleManager.mm",
        "RCTBridgeModuleNameForClass(module))", "RCTBridgeModuleNameForClass(Class(module)))")
  end`

**Comment by oleksandr-shvetsov-qb** [comment]
@Nirmal-ICPL
Could you please confirm that you have tried to reload application? I mean not rebuild, but only reload static assets for the application by pressing "Reload" in  [developer menu](https://reactnative.dev/docs/debugging#accessing-the-in-app-developer-menu)?

**Comment by Nirmal-ICPL** [comment]
@oleksandr-shvetsov-qb 

Yes, I tried to reload the page. That buttons are not coming i.e. not able to view call button images. But i pressed at that area and was able to verify call feature.

**Comment by oleksandr-shvetsov-qb** [comment]
@Nirmal-ICPL
You can try to change paths in [src/images.js](https://github.com/QuickBlox/quickblox-react-native-samples/blob/master/webrtc-sample/src/images.js) to the relative paths to see if this helps.

**Comment by Nirmal-ICPL** [comment]
Yes, it works now..Thanks
