### ISSUE TITLE
A problem occurred configuring project ':quickblox-react-native-sdk'.

### ISSUE THREAD

**Issue by krunal-sisnolabs** [QuickBlox/quickblox-react-native-samples#28]
I clone this project. run "npm install" and then run "cd android && ./gradlew clean && cd .."

How Can I solve this error?

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':quickblox-react-native-sdk'.
> Could not resolve all artifacts for configuration ':quickblox-react-native-sdk:classpath'.
   > Could not resolve com.android.tools.ddms:ddmlib:26.3.1.
     Required by:
         project :quickblox-react-native-sdk > com.android.tools.build:gradle:3.3.1 > com.android.tools.build:builder:3.3.1
         project :quickblox-react-native-sdk > com.android.tools.build:gradle:3.3.1 > com.android.tools.build:builder:3.3.1 > com.android.tools.build:builder-test-api:3.3.1
         project :quickblox-react-native-sdk > com.android.tools.build:gradle:3.3.1 > com.android.tools.build:builder:3.3.1 > com.android.tools:sdk-common:26.3.1
      > Could not resolve com.android.tools.ddms:ddmlib:26.3.1.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/ddms/ddmlib/26.3.1/ddmlib-26.3.1.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/com/android/tools/ddms/ddmlib/26.3.1/ddmlib-26.3.1.pom'.
               > Read timed out
   > Could not resolve com.android.tools.analytics-library:tracker:26.3.1.
     Required by:
         project :quickblox-react-native-sdk > com.android.tools.build:gradle:3.3.1 > com.android.tools.build:builder:3.3.1
      > Could not resolve com.android.tools.analytics-library:tracker:26.3.1.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/analytics-library/tracker/26.3.1/tracker-26.3.1.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/com/android/tools/analytics-library/tracker/26.3.1/tracker-26.3.1.pom'.
               > Read timed out
   > Could not resolve com.google.guava:guava:26.0-jre.
     Required by:
         project :quickblox-react-native-sdk > com.android.tools.build:gradle:3.3.1 > com.android.tools.analytics-library:shared:26.3.1
         project :quickblox-react-native-sdk > com.android.tools.build:gradle:3.3.1 > com.android.tools.analytics-library:crash:26.3.1
         project :quickblox-react-native-sdk > com.android.tools.build:gradle:3.3.1 > com.android.tools.lint:lint-gradle-api:26.3.1
         project :quickblox-react-native-sdk > com.android.tools.build:gradle:3.3.1 > com.android.tools.build:gradle-api:3.3.1
         project :quickblox-react-native-sdk > com.android.tools.build:gradle:3.3.1 > androidx.databinding:databinding-compiler-common:3.3.1
         project :quickblox-react-native-sdk > com.android.tools.build:gradle:3.3.1 > com.android.tools.build:bundletool:0.6.0
         project :quickblox-react-native-sdk > com.android.tools.build:gradle:3.3.1 > com.android.tools.build:builder:3.3.1 > com.android.tools:common:26.3.1
      > Skipped due to earlier error
   > Could not resolve org.jetbrains.kotlin:kotlin-reflect:1.3.20.
     Required by:
         project :quickblox-react-native-sdk > com.android.tools.build:gradle:3.3.1 > com.android.tools.lint:lint-gradle-api:26.3.1
         project :quickblox-react-native-sdk > com.android.tools.build:gradle:3.3.1 > com.android.tools.build:builder:3.3.1 > com.android.tools:sdk-common:26.3.1
      > Skipped due to earlier error
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.3.20.
     Required by:
         project :quickblox-react-native-sdk > com.android.tools.build:gradle:3.3.1 > org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.20
      > Skipped due to earlier error
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.20.
     Required by:
         project :quickblox-react-native-sdk > com.android.tools.build:gradle:3.3.1 > org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.20
      > Skipped due to earlier error
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.3.20.
     Required by:
         project :quickblox-react-native-sdk > com.android.tools.build:gradle:3.3.1 > com.android.tools.build.jetifier:jetifier-core:1.0.0-beta02
         project :quickblox-react-native-sdk > com.android.tools.build:gradle:3.3.1 > com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta02
      > Skipped due to earlier error
   > Could not resolve com.google.guava:guava:26.0-jre.
     Required by:
         project :quickblox-react-native-sdk > com.android.tools.build:gradle:3.3.1 > com.android.tools.build:builder:3.3.1 > com.android.tools.build:apkzlib:3.3.1
      > Skipped due to earlier error
   > Could not resolve com.google.guava:guava:26.0-jre.
     Required by:
         project :quickblox-react-native-sdk > com.android.tools.build:gradle:3.3.1 > com.android.tools.build:bundletool:0.6.0 > com.google.protobuf:protobuf-java-util:3.4.0
      > Skipped due to earlier error
   > Could not resolve com.google.guava:guava:26.0-jre.
     Required by:
         project :quickblox-react-native-sdk > com.android.tools.build:gradle:3.3.1 > com.android.tools.build:builder:3.3.1 > com.android.tools:sdklib:26.3.1 > com.android.tools:repository:26.3.1 > com.google.jimfs:jimfs:1.1
      > Skipped due to earlier error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 17s

**Comment by oleksandr-shvetsov-qb** [comment]
Hello @krunal-sisnolabs,
According to messages from your logs
```
> Could not get resource 'https://jcenter.bintray.com/com/android/tools/ddms/ddmlib/26.3.1/ddmlib-26.3.1.pom'.
> Could not HEAD 'https://jcenter.bintray.com/com/android/tools/ddms/ddmlib/26.3.1/ddmlib-26.3.1.pom'.
> Read timed out
```
it seems that `jcenter` repo was not available.
