### ISSUE TITLE
Audio very low

### ISSUE THREAD

**Issue by LhuizF** [QuickBlox/quickblox-react-native-samples#57]
Hello,
I'm making a call from the web to the android app, but the audio that comes out on andoird is very low, what could be causing this?

**Comment by kirillTolmachev** [comment]
Hello @LhuizF 
On the Android side please try to change the audio output like in our documentation.
https://docs.quickblox.com/docs/react-native-video-calling-advanced#switch-audio-output

**Comment by LhuizF** [comment]
Hello @kirillTolmachev, thanks for the reply, 
Even following the documentation and calling the function to use the speaker, it didn't change the volume :(
