### ISSUE TITLE
Push Notification Issue: When clicking on a notification, neither onNotificationOpenedApp nor getInitialNotification is being called.

### ISSUE THREAD

**Issue by AndyDesign999** [QuickBlox/quickblox-react-native-samples#63]
In the Android platform, messaging().onMessage() is working as expected, but onNotificationOpenedApp and getInitialNotification are not functioning as anticipated. I aim to manage navigation to the chat room screen when the user opens the app by clicking on the notification.

```
const onNotificationOpenedAppFromBackground = async () => {
    const unsubscribe = messaging().onNotificationOpenedApp(
      async remoteMessage => {
        console.log(
          'App opened from BACKGROUND by tapping notification:',
          JSON.stringify(remoteMessage),
        );
      },
    );
    return unsubscribe;
  };

  const onNotificationOpenedAppFromQuit = async () => {
    const message = await messaging().getInitialNotification();

    if (message) {
      console.log(
        'App opened from QUIT by tapping notification:',
        JSON.stringify(message),
      );
    }
  };
```

**Comment by VladimirNybozhinsky** [comment]
@AndyDesign999  Hi!
 This is Vladimir from QuickBlox.

If I understand correctly, you use Firebase to send and receive push notifications. We have not yet implemented this functionality in our samples. Perhaps this [article](https://medium.com/@dirussogaetano/push-notifications-react-native-3ebdfa33fe49) will help you.

Best regards, Vladimir

**Comment by AndyDesign999** [comment]
@VladimirNybozhinsky I want to achieve navigation to a particular screen when clicking on a QuickBlox chat notification. I don't find any code in the sample. How can I achieve it?

**Comment by VladimirNybozhinsky** [comment]
Hi @AndyDesign999!
In RN Chat Sample, the following packages are used to receive push notifications:
```
import PushNotification, {Importance} from 'react-native-push-notification';
import PushNotificationIOS from '@react-native-community/push-notification-ios'; 
```
RN Chat Sample has not yet implemented the functionality of opening a specific screen by clicking on a push notification.
  But you can implement this yourself using the example shown in the [documentation](https://www.npmjs.com/package/@react-native-community/push-notification-ios) "@react-native-community/push-notification-ios"

You can also not use the libraries from the sample and use other resources for this, for example Firebase, the code from which you provided in the question.

You can also ask this question in our discord in the React Native channel
https://discord.gg/RvkCR3kT

Best regards, Vladimir

**Comment by AndyDesign999** [comment]
@VladimirNybozhinsky Thanks!
